package org.openapitools.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.security.SecurityScheme;

/**
 * SpringDoc（OpenAPI 3）の基本的な設定を行うクラス。
 *
 * このクラスは、生成されるAPIドキュメントのメタデータを定義します。
 * `apiInfo` Beanを通じて、APIのタイトル、説明、バージョンなどの
 * 基本的な情報を設定します。これにより、Swagger UIなどのツールで
 * 表示されるAPIドキュメントが、より分かりやすく、情報量豊かなものになります。
 */
@Configuration
public class SpringDocConfiguration {

    @Bean(name = "org.openapitools.configuration.SpringDocConfiguration.apiInfo")
    OpenAPI apiInfo() {
        return new OpenAPI()
                .info(
                        new Info()
                                .title("Todo API")
                                .description(
                                        "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)")
                                .version("0.1.0"));
    }
}
